env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
rules: {
  # 字符串：单引号 + 反引号
  "@typescript-eslint/quotes": ["error", "single", { "allowTemplateLiterals": true }],
  # 缩进：4
  "@typescript-eslint/indent": ["error", 4],
  # 换行符：\r
  "eol-last": ["error", "always"],
  # 尾随逗号：数组；对象
  "@typescript-eslint/comma-dangle": ["error", { "arrays": "always", "objects": "always" }],
  "@typescript-eslint/space-before-function-paren": ["error", "never"],
  "@typescript-eslint/member-delimiter-style": ["error", "semi"],
  "max-len": ["error", 120],
}
