env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
rules: {
  # 字符串：单引号 + 反引号
  "@typescript-eslint/quotes": ["error", "single", { "allowTemplateLiterals": true }],
  # 缩进：4
  "@typescript-eslint/indent": ["error", 4],
  # 换行符：\r
  "eol-last": ["error", "always"],
  # 尾随逗号：数组；对象
  "@typescript-eslint/comma-dangle": ["error", { "arrays": "only-multiline", "objects": "only-multiline", "enums": "only-multiline" }],
  "@typescript-eslint/space-before-function-paren": ["error", { "anonymous": "always", "named": "never", "asyncArrow": "always" }],
  "@typescript-eslint/semi": ["error", "always"],
  "@typescript-eslint/member-delimiter-style": ["error", { "multiline": { "delimiter": "semi", "requireLast": true } }],
  "max-len": ["error", 120],
}
